package postgres

const createEventsTable = `
CREATE TABLE IF NOT EXISTS trail_events (
    event_time timestamptz NOT NULL,
    event_id bytea PRIMARY KEY CHECK (octet_length(event_id) = 16),
    batch_id bytea NOT NULL CHECK (octet_length(batch_id) = 16),
    jetstream_stream text NOT NULL DEFAULT '',
    jetstream_stream_seq bigint NOT NULL DEFAULT 0,
    jetstream_consumer text NOT NULL DEFAULT '',
    jetstream_consumer_seq bigint NOT NULL DEFAULT 0,
    jetstream_delivered bigint NOT NULL DEFAULT 0,
    received_at timestamptz NOT NULL,
    ingested_at timestamptz NOT NULL DEFAULT now(),
    service text NOT NULL,
    environment text NOT NULL,
    version text NOT NULL DEFAULT '',
    kind text NOT NULL,
    level text NOT NULL,
    flow_id bytea CHECK (flow_id IS NULL OR octet_length(flow_id) = 16),
    execution_id bytea CHECK (execution_id IS NULL OR octet_length(execution_id) = 16),
    parent_execution_id bytea CHECK (parent_execution_id IS NULL OR octet_length(parent_execution_id) = 16),
    retry_of_execution_id bytea CHECK (retry_of_execution_id IS NULL OR octet_length(retry_of_execution_id) = 16),
    execution_attempt integer NOT NULL DEFAULT 0,
    execution_source text NOT NULL DEFAULT '',
    entity_type text NOT NULL DEFAULT '',
    entity_id text NOT NULL DEFAULT '',
    parent_event_id bytea CHECK (parent_event_id IS NULL OR octet_length(parent_event_id) = 16),
    flow_status text NOT NULL DEFAULT '',
    execution_status text NOT NULL DEFAULT '',
    execution_kind text NOT NULL DEFAULT '',
    fields jsonb NOT NULL DEFAULT '[]'::jsonb,
    http_method text NOT NULL DEFAULT '',
    http_scheme text NOT NULL DEFAULT '',
    http_host text NOT NULL DEFAULT '',
    http_path text NOT NULL DEFAULT '',
    http_status_code integer NOT NULL DEFAULT 0,
    http_duration_ns bigint NOT NULL DEFAULT 0,
    http_success boolean NOT NULL DEFAULT false,
    http_request_size bigint NOT NULL DEFAULT 0,
    http_response_size bigint NOT NULL DEFAULT 0,
    http_request_preview text NOT NULL DEFAULT '',
    http_response_preview text NOT NULL DEFAULT '',
    payload_refs jsonb NOT NULL DEFAULT '[]'::jsonb
)`

var migrationStatements = []string{
	createEventsTable,
	`CREATE INDEX IF NOT EXISTS trail_events_time_idx ON trail_events (event_time DESC, event_id DESC)`,
	`CREATE INDEX IF NOT EXISTS trail_events_flow_idx ON trail_events (flow_id, event_time, event_id) WHERE flow_id IS NOT NULL`,
	`CREATE INDEX IF NOT EXISTS trail_events_execution_idx ON trail_events (execution_id, event_time, event_id) WHERE execution_id IS NOT NULL`,
	`CREATE INDEX IF NOT EXISTS trail_events_entity_idx ON trail_events (entity_type, entity_id, event_time DESC) WHERE entity_type <> '' AND entity_id <> ''`,
	`CREATE INDEX IF NOT EXISTS trail_events_kind_time_idx ON trail_events (kind, event_time DESC)`,
	`CREATE INDEX IF NOT EXISTS trail_events_failed_execution_idx ON trail_events (event_time DESC, execution_id) WHERE execution_status = 'failed'`,
	`CREATE INDEX IF NOT EXISTS trail_events_http_5xx_idx ON trail_events (event_time DESC, http_status_code) WHERE http_status_code >= 500`,
	`CREATE INDEX IF NOT EXISTS trail_events_retry_idx ON trail_events (retry_of_execution_id, execution_id) WHERE retry_of_execution_id IS NOT NULL`,
}
